const encoder=new TextEncoder(),decoder=new TextDecoder("utf-8",{fatal:true});
export const MACHINE_PROVIDER_PROTOCOL="cmux.machine-provider" as const,MACHINE_PROVIDER_VERSION=1 as const,CMUX_HANDOFF_PROTOCOL=10 as const,MAX_CONTROL_FRAME_BYTES=1_048_576,MAX_CMUX_FRAME_BYTES=67_108_864,MAX_OPAQUE_BYTES=512,MAX_ERROR_CODE_BYTES=64;
export const PROVIDER_METHODS=["hello","negotiate_client_capabilities","subscribe_notices","acknowledge_notice","snapshot","open_machine","select_scope","create_machine","connect_external_machine","machine_lifecycle_snapshot","rename_machine","delete_machine","restore_machine","purge_machine","create_workspace","workspace_snapshot","rename_workspace","delete_workspace","restore_workspace","purge_workspace","invoke_action","close_machine"] as const;
export type ProviderMethod=typeof PROVIDER_METHODS[number];
export const PROVIDER_CAPABILITIES=["connect-external-machine-v1","machine-lifecycle-v1","workspace-lifecycle-v1","workspace-mirror-authority-v1","durable-notices-v1","client-capability-negotiation-v1"] as const,PROVIDER_ACTION_TARGETS_CLIENT_CAPABILITY="provider-action-targets-v1";
export type WireValue=null|boolean|number|bigint|string|readonly WireValue[]|{readonly[key:string]:WireValue};
export interface ProviderRequestEnvelope<M extends ProviderMethod=ProviderMethod>{readonly protocol:typeof MACHINE_PROVIDER_PROTOCOL;readonly version:1;readonly id:string;readonly method:M;readonly params:Readonly<Record<string,WireValue>>}
export interface ProviderError{readonly code:string;readonly message:string;readonly retryable:boolean}
export interface ProviderResponseEnvelope<T extends WireValue=WireValue>{readonly protocol:typeof MACHINE_PROVIDER_PROTOCOL;readonly version:1;readonly id:string;readonly capabilities?:readonly string[];readonly result?:T;readonly error?:ProviderError}
export interface ProviderEventEnvelope{readonly protocol:typeof MACHINE_PROVIDER_PROTOCOL;readonly version:1;readonly delivery?:{notice_id:string;sequence:bigint};readonly event:"snapshot_changed"|"connection_closed"|"notice";readonly params:Readonly<Record<string,WireValue>>}
export interface TransportHandshake{readonly protocol:typeof MACHINE_PROVIDER_PROTOCOL;readonly version:1;readonly role:"transport";readonly token:string;readonly ticket:string}
export class ProviderCodecError extends TypeError{constructor(m:string){super(m);this.name="ProviderCodecError"}}const fail=(m:string):never=>{throw new ProviderCodecError(m)};
const obj=(v:unknown,n:string):Record<string,unknown>=>{if(!v||typeof v!=="object"||Array.isArray(v)||(Object.getPrototypeOf(v)!==Object.prototype&&Object.getPrototypeOf(v)!==null))fail(`${n} must be an object`);return v as Record<string,unknown>},exact=(v:Record<string,unknown>,r:readonly string[],o:readonly string[],n:string)=>{for(const k of r)if(!(k in v))fail(`${n}.${k} is required`);for(const k of Object.keys(v))if(!r.includes(k)&&!o.includes(k))fail(`${n}.${k} is not allowed`)},opaque=(v:unknown,n:string):string=>{if(typeof v!=="string"||encoder.encode(v).byteLength<1||encoder.encode(v).byteLength>512||/[\p{Cc}]/u.test(v))fail(`${n} is invalid`);return v as string},text=(v:unknown,n:string):string=>typeof v==="string"?v:fail(`${n} must be a string`),bool=(v:unknown,n:string):boolean=>typeof v==="boolean"?v:fail(`${n} must be boolean`),integer=(v:unknown,min:bigint,max:bigint,n:string):bigint=>{const x=typeof v==="bigint"?v:typeof v==="number"&&Number.isSafeInteger(v)?BigInt(v):fail(`${n} must be integer`);if(x<min||x>max)fail(`${n} outside range`);return x},u64=(v:unknown,n:string)=>integer(v,0n,18_446_744_073_709_551_615n,n),i64=(v:unknown,n:string)=>integer(v,-9_223_372_036_854_775_808n,9_223_372_036_854_775_807n,n),en=<T extends string>(v:unknown,a:readonly T[],n:string):T=>typeof v==="string"&&a.includes(v as T)?v as T:fail(`${n} unsupported`),arr=<T>(v:unknown,n:string,d:(x:unknown,n:string)=>T):T[]=>Array.isArray(v)?v.map((x,i)=>d(x,`${n}[${i}]`)):fail(`${n} must be array`);
type D=(v:unknown,n:string)=>WireValue;type F=readonly[D,boolean?];const shape=(f:Readonly<Record<string,F>>):D=>(v,n)=>{const r=obj(v,n),req=Object.entries(f).filter(([,x])=>!x[1]).map(x=>x[0]),opt=Object.entries(f).filter(([,x])=>x[1]).map(x=>x[0]);exact(r,req,opt,n);const out:Record<string,WireValue>={};for(const[k,[d]]of Object.entries(f))if(r[k]!==undefined)out[k]=d(r[k],`${n}.${k}`);return out};const dOpaque:D=opaque,dText:D=text,dBool:D=bool,dU64:D=u64,dI64:D=i64,dStrings:D=(v,n)=>arr(v,n,text);
const notice=shape({level:[(v,n)=>en(v,["info","warning","error"] as const,n)],message:[dText]}),caps=shape({rename:[dBool,true],delete:[dBool,true],restore:[dBool,true],purge:[dBool,true]}),policy:D=(v,n)=>{const r=obj(v,n),owner=en(r.owner,["session","provider"] as const,`${n}.owner`);if(owner==="session"){exact(r,["owner"],[],n);const sessionPolicy:Record<string,WireValue>={owner};return sessionPolicy}exact(r,["owner","default_mode","modes"],[],n);const providerPolicy:Record<string,WireValue>={owner,default_mode:en(r.default_mode,["isolated","host"] as const,n),modes:arr(r.modes,n,(x,xn)=>en(x,["isolated","host"] as const,xn))};return providerPolicy},scope=shape({id:[dOpaque],display_name:[dText],kind:[(v,n)=>en(v,["personal","team"] as const,n)],can_admin:[dBool]}),machine=shape({id:[dOpaque],display_name:[dText],subtitle:[dText,true],status:[(v,n)=>en(v,["running","connecting","sleeping","stopped","unavailable"] as const,n)],connectable:[dBool],workspace_create:[policy]}),field=shape({id:[dText],kind:[(v,n)=>en(v,["text","email","integer"] as const,n)],label:[dText],required:[dBool,true],max_length:[(v,n)=>integer(v,0n,4_294_967_295n,n),true],minimum:[dI64,true],maximum:[dI64,true],placeholder:[dText,true]}),action=shape({id:[dOpaque],label:[dText],target:[(v)=>typeof v==="string"&&["scope","selected_machine","selected_workspace"].includes(v)?v:"unsupported",true],destructive:[dBool,true],fields:[(v,n)=>arr(v,n,field),true]}),snapshot=shape({revision:[dU64],scopes:[(v,n)=>arr(v,n,scope)],selected_scope_id:[dOpaque],machines:[(v,n)=>arr(v,n,machine)],selected_machine_id:[dOpaque,true],capabilities:[shape({create_machine:[dBool,true],connect_external_machine:[dBool,true]})],actions:[(v,n)=>arr(v,n,action),true],notice:[notice,true]}),transport=shape({kind:[(v,n)=>en(v,["provider_stream"] as const,n)],ticket:[dOpaque],expires_at:[dText]}),machineLife=shape({id:[dOpaque],display_name:[dText],status:[(v,n)=>en(v,["active","recoverable"] as const,n)],version:[dU64],recoverable_until:[dText,true],capabilities:[caps]}),workspaceLife=shape({id:[dOpaque],display_name:[dText],mode:[(v,n)=>en(v,["isolated","host"] as const,n)],status:[(v,n)=>en(v,["active","recoverable"] as const,n)],version:[dU64],recoverable_until:[dText,true],capabilities:[caps]}),values:D=(v,n)=>{const r=obj(v,n),o:Record<string,WireValue>={};for(const[k,x]of Object.entries(r))o[k]=typeof x==="string"||typeof x==="boolean"?x:i64(x,`${n}.${k}`);return o},mm=shape({scope_id:[dOpaque],machine_id:[dOpaque],expected_version:[dU64],mutation_id:[dOpaque]}),wm=shape({machine_id:[dOpaque],workspace_id:[dOpaque],expected_version:[dU64],mutation_id:[dOpaque]});
export const requestDecoders:Record<ProviderMethod,D>={hello:shape({token:[dOpaque],client:[shape({name:[dText],version:[dText],supported_versions:[(v,n)=>arr(v,n,(x,xn)=>Number(integer(x,0n,65535n,xn)))]})]}),negotiate_client_capabilities:shape({capabilities:[dStrings]}),subscribe_notices:shape({consumer_id:[dOpaque]}),acknowledge_notice:shape({notice_id:[dOpaque],sequence:[dU64]}),snapshot:shape({known_revision:[dU64,true]}),open_machine:shape({machine_id:[dOpaque],workspace_mirror_authority:[dBool,true]}),select_scope:shape({scope_id:[dOpaque]}),create_machine:shape({scope_id:[dOpaque],mutation_id:[dOpaque]}),connect_external_machine:shape({scope_id:[dOpaque],specifier:[(v,n)=>{const x=opaque(v,n);if(x.trim()!==x)fail(`${n} whitespace`);return x}],mutation_id:[dOpaque]}),machine_lifecycle_snapshot:shape({scope_id:[dOpaque],known_revision:[dU64,true]}),rename_machine:shape({scope_id:[dOpaque],machine_id:[dOpaque],expected_version:[dU64],display_name:[dText],mutation_id:[dOpaque]}),delete_machine:mm,restore_machine:mm,purge_machine:mm,create_workspace:shape({machine_id:[dOpaque],mode:[(v,n)=>en(v,["isolated","host"] as const,n)],mutation_id:[dOpaque]}),workspace_snapshot:shape({machine_id:[dOpaque],known_revision:[dU64,true]}),rename_workspace:shape({machine_id:[dOpaque],workspace_id:[dOpaque],expected_version:[dU64],display_name:[dText],mutation_id:[dOpaque]}),delete_workspace:wm,restore_workspace:wm,purge_workspace:wm,invoke_action:shape({action_id:[dOpaque],values:[values,true],machine_id:[dOpaque,true],workspace_id:[dOpaque,true],mutation_id:[dOpaque]}),close_machine:shape({connection_id:[dOpaque]})};
const mr=shape({machine_id:[dOpaque],version:[dU64],revision:[dU64],notice:[notice,true]}),wr=shape({workspace_id:[dOpaque],version:[dU64],revision:[dU64],notice:[notice,true]});export const resultDecoders:Record<ProviderMethod,D>={hello:shape({provider_id:[dOpaque],provider_name:[dText],negotiated_version:[(v,n)=>Number(integer(v,1n,1n,n))]}),negotiate_client_capabilities:shape({capabilities:[dStrings]}),subscribe_notices:shape({sequence:[dU64]}),acknowledge_notice:shape({sequence:[dU64]}),snapshot,open_machine:shape({connection_id:[dOpaque],transport:[transport],workspace_mirror_authority:[dOpaque,true]}),select_scope:shape({snapshot:[snapshot]}),create_machine:shape({machine_id:[dOpaque],revision:[dU64],notice:[notice,true]}),connect_external_machine:shape({machine_id:[dOpaque],revision:[dU64],notice:[notice,true]}),machine_lifecycle_snapshot:shape({revision:[dU64],scope_id:[dOpaque],machines:[(v,n)=>arr(v,n,machineLife)]}),rename_machine:mr,delete_machine:mr,restore_machine:mr,purge_machine:mr,create_workspace:shape({revision:[dU64],notice:[notice,true]}),workspace_snapshot:shape({revision:[dU64],machine_id:[dOpaque],workspaces:[(v,n)=>arr(v,n,workspaceLife)]}),rename_workspace:wr,delete_workspace:wr,restore_workspace:wr,purge_workspace:wr,invoke_action:shape({revision:[dU64],notice:[notice,true],url:[dText,true],selected_scope_id:[dOpaque,true],selected_machine_id:[dOpaque,true]}),close_machine:shape({revision:[dU64]})};
class Parser{at=0;readonly s:string;constructor(s:string){this.s=s}parse(){const v=this.val(0);this.ws();if(this.at!==this.s.length)fail("trailing data");return v}ws(){while(/[\x20\t\r\n]/.test(this.s[this.at]??""))this.at++}val(d:number):unknown{if(d>64)fail("too deep");this.ws();const c=this.s[this.at];if(c==='"')return this.str();if(c==='{')return this.ob(d+1);if(c==='[')return this.ar(d+1);for(const[w,v]of [["true",true],["false",false],["null",null]] as const)if(this.s.startsWith(w,this.at)){this.at+=w.length;return v}return this.num()}str(){const st=this.at++;let e=false;while(this.at<this.s.length){const c=this.s[this.at++];if(!e&&c==='"'){try{return JSON.parse(this.s.slice(st,this.at)) as string}catch{return fail("bad string")}}e=!e&&c==='\\'}return fail("unterminated string")}num(){const found=/^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?/.exec(this.s.slice(this.at));if(!found)fail("bad value");const m=found as RegExpExecArray;this.at+=m[0].length;if(/[.eE]/.test(m[0])){const n=Number(m[0]);return Number.isFinite(n)?n:fail("nonfinite")}const n=BigInt(m[0]);return n>=BigInt(Number.MIN_SAFE_INTEGER)&&n<=BigInt(Number.MAX_SAFE_INTEGER)?Number(n):n}ob(d:number){this.at++;this.ws();const o=Object.create(null) as Record<string,unknown>;if(this.s[this.at]==='}'){this.at++;return o}for(;;){this.ws();if(this.s[this.at]!=='"')fail("key required");const k=this.str();this.ws();if(this.s[this.at++]!==':')fail("colon required");if(Object.hasOwn(o,k))fail("duplicate key");o[k]=this.val(d);this.ws();const c=this.s[this.at++];if(c==='}')return o;if(c!==',')fail("comma required")}}ar(d:number){this.at++;this.ws();const a:unknown[]=[];if(this.s[this.at]===']'){this.at++;return a}for(;;){a.push(this.val(d));this.ws();const c=this.s[this.at++];if(c===']')return a;if(c!==',')fail("comma required")}}}
const parse=(b:Uint8Array)=>{if(!b.byteLength||b.byteLength>MAX_CONTROL_FRAME_BYTES)fail("frame size");let s:string;try{s=decoder.decode(b)}catch{return fail("utf8")};if(s.includes("\n")||s.includes("\r"))fail("delimiter included");return new Parser(s).parse()},json=(v:unknown):string=>{if(v===null)return"null";if(typeof v==="bigint")return`${v}`;if(typeof v==="number"||typeof v==="boolean"||typeof v==="string")return JSON.stringify(v);if(Array.isArray(v))return`[${v.map(json)}]`;return`{${Object.entries(obj(v,"value")).filter(([,x])=>x!==undefined).map(([k,x])=>`${JSON.stringify(k)}:${json(x)}`)}}`},line=(v:unknown)=>{const b=encoder.encode(`${json(v)}\n`);if(b.byteLength>MAX_CONTROL_FRAME_BYTES)fail("too large");return b},base=(v:unknown,n:string)=>{const r=obj(v,n);if(r.protocol!==MACHINE_PROVIDER_PROTOCOL||integer(r.version,1n,1n,`${n}.version`)!==1n)fail("protocol");return r};
function normalizedRequestParams(method:ProviderMethod,value:unknown):Record<string,WireValue>{
 const decoded=requestDecoders[method](value,"params") as Record<string,WireValue>;
 if(method!=="invoke_action")return decoded;
 const rawParams=obj(value,"params"),rawValues=rawParams.values;
 if(rawValues===undefined)return decoded;
 const safe=Object.create(null) as Record<string,WireValue>;
 for(const[key,item]of Object.entries(obj(rawValues,"params.values"))){
  const normalized=typeof item==="string"||typeof item==="boolean"?item:i64(item,`params.values.${key}`);
  Object.defineProperty(safe,key,{value:normalized,enumerable:true,writable:false,configurable:false});
 }
 decoded.values=safe;
 return decoded;
}
export function decodeProviderRequestFrame(b:Uint8Array):ProviderRequestEnvelope{const r=base(parse(b),"request"),method=en(r.method,PROVIDER_METHODS,"method");return{protocol:MACHINE_PROVIDER_PROTOCOL,version:1,id:opaque(r.id,"id"),method,params:normalizedRequestParams(method,r.params)}}export const encodeProviderRequest=(r:ProviderRequestEnvelope)=>line({protocol:MACHINE_PROVIDER_PROTOCOL,version:1,id:opaque(r.id,"id"),method:r.method,params:normalizedRequestParams(r.method,r.params)});
const err=(v:unknown):ProviderError=>{const r=obj(v,"error");exact(r,["code","message","retryable"],[],"error");const code=text(r.code,"code");if(!/^[a-z0-9_.-]{1,64}$/.test(code))fail("code");return{code,message:text(r.message,"message"),retryable:bool(r.retryable,"retryable")}};export function decodeProviderResponseFrame(b:Uint8Array,m:ProviderMethod):ProviderResponseEnvelope{const r=base(parse(b),"response"),has="result"in r,e="error"in r;if(has===e)fail("result xor error");const x={protocol:MACHINE_PROVIDER_PROTOCOL,version:1 as const,id:opaque(r.id,"id"),...(r.capabilities===undefined?{}:{capabilities:arr(r.capabilities,"capabilities",text)})};return e?{...x,error:err(r.error)}:{...x,result:resultDecoders[m](r.result,"result")}}export const encodeProviderSuccess=(id:string,result:WireValue,capabilities?:readonly string[])=>line({protocol:MACHINE_PROVIDER_PROTOCOL,version:1,id:opaque(id,"id"),...(capabilities?.length?{capabilities}:{}),result}),encodeProviderFailure=(id:string,error:ProviderError)=>line({protocol:MACHINE_PROVIDER_PROTOCOL,version:1,id:opaque(id,"id"),error:err(error)});
export function decodeProviderEventFrame(b:Uint8Array):ProviderEventEnvelope{const r=base(parse(b),"event"),event=en(r.event,["snapshot_changed","connection_closed","notice"] as const,"event"),d=event==="snapshot_changed"?shape({revision:[dU64]}):event==="connection_closed"?shape({connection_id:[dOpaque],machine_id:[dOpaque],reason:[dText]}):notice,delivery=r.delivery===undefined?undefined:shape({notice_id:[dOpaque],sequence:[dU64]})(r.delivery,"delivery") as{notice_id:string;sequence:bigint};return{protocol:MACHINE_PROVIDER_PROTOCOL,version:1,...(delivery?{delivery}:{}),event,params:d(r.params,"params") as Record<string,WireValue>}}export const encodeProviderEvent=(e:{event:ProviderEventEnvelope["event"];params:Record<string,WireValue>},delivery?:ProviderEventEnvelope["delivery"])=>line({protocol:MACHINE_PROVIDER_PROTOCOL,version:1,...(delivery?{delivery}:{}),event:e.event,params:e.params});
export function decodeTransportHandshakeFrame(b:Uint8Array):TransportHandshake{const r=obj(parse(b),"handshake");exact(r,["protocol","version","role","token","ticket"],[],"handshake");if(r.protocol!==MACHINE_PROVIDER_PROTOCOL||integer(r.version,1n,1n,"version")!==1n||r.role!=="transport")fail("handshake");return{protocol:MACHINE_PROVIDER_PROTOCOL,version:1,role:"transport",token:opaque(r.token,"token"),ticket:opaque(r.ticket,"ticket")}}export const encodeTransportHandshake=(h:TransportHandshake)=>line(decodeTransportHandshakeFrame(encoder.encode(json(h)))),encodeTransportHandshakeResult=(accepted:boolean)=>line({accepted:bool(accepted,"accepted")});export function retainActionsForClientCapabilities<T extends{actions?:readonly{target?:string}[]}>(s:T,c:readonly string[]):T{return c.includes(PROVIDER_ACTION_TARGETS_CLIENT_CAPABILITY)?s:{...s,actions:(s.actions??[]).filter(a=>a.target===undefined||a.target==="scope")} as T}
export function encodeProviderResultSuccess(method:ProviderMethod,id:string,result:WireValue,capabilities?:readonly string[]):Uint8Array{return encodeProviderSuccess(id,resultDecoders[method](result,"result"),capabilities)}
export function decodeTransportHandshakeResultFrame(bytes:Uint8Array):{readonly accepted:boolean}{const raw=obj(parse(bytes),"handshake result");exact(raw,["accepted"],[],"handshake result");return{accepted:bool(raw.accepted,"handshake result.accepted")}}
