import { descriptor, type CommandDescriptorGroup } from "./types.js";

export const PREVIEW_COMMAND_DESCRIPTORS: CommandDescriptorGroup = {
  "preview.launch": descriptor("preview.control", "session", "optional", "session", "challenge"),
  "preview.state": descriptor("preview.read", "session", "optional", "session", "none"),
  "preview.activate": descriptor("preview.control", "session", "optional", "session", "none"),
  "preview.navigate": descriptor("preview.control", "session", "optional", "session", "challenge"),
  "preview.back": descriptor("preview.control", "session", "optional", "session", "none"),
  "preview.forward": descriptor("preview.control", "session", "optional", "session", "none"),
  "preview.reload": descriptor("preview.control", "session", "optional", "session", "none"),
  "preview.close": descriptor("preview.control", "session", "optional", "session", "none"),
  "preview.capture": descriptor("preview.read", "session", "optional", "session", "none"),
  "preview.capture.read": descriptor("preview.read", "session", "none", "none", "none"),
  "preview.click": descriptor("preview.input", "session", "optional", "session", "none"),
  "preview.fill": descriptor("preview.input", "session", "optional", "session", "none"),
  "preview.scroll": descriptor("preview.input", "session", "optional", "session", "none"),
  "preview.type": descriptor("preview.input", "session", "optional", "session", "none"),
  "preview.select": descriptor("preview.input", "session", "optional", "session", "none"),
  "preview.press": descriptor("preview.input", "session", "optional", "session", "none"),
  "preview.upload": descriptor("preview.input", "session", "optional", "session", "challenge"),
  "preview.policy.check": descriptor("preview.read", "session", "none", "none", "none"),
  "preview.lease.acquire": descriptor("preview.control", "session", "optional", "session", "none"),
  "preview.lease.renew": descriptor("preview.control", "session", "optional", "session", "none"),
  "preview.lease.release": descriptor("preview.control", "session", "optional", "session", "none"),
  "preview.handoff": descriptor("preview.control", "session", "optional", "session", "none"),
};
