import { descriptor, type CommandDescriptorGroup } from "./types.js";

export const RUNTIME_WORKSPACE_COMMAND_DESCRIPTORS: CommandDescriptorGroup = {
  "runtime.list": descriptor("sessions.read", "host", "none", "none", "none"),
  "workspace.list": descriptor("sessions.read", "host", "none", "none", "none"),
  "workspace.create": descriptor("sessions.manage", "host", "none", "none", "none"),
  "workspace.import": descriptor("sessions.manage", "host", "none", "none", "none"),
  "workspace.archive": descriptor("sessions.manage", "host", "none", "none", "challenge"),
  "workspace.recover": descriptor("sessions.manage", "host", "none", "none", "none"),
  "host.list": descriptor("sessions.read", "host", "none", "none", "none"),
  "session.list": descriptor("sessions.read", "host", "none", "none", "none"),
  "transcript.search": descriptor("sessions.read", "host", "none", "none", "none"),
  "transcript.context": descriptor("sessions.read", "session", "none", "none", "none"),
  "transcript.page": descriptor("sessions.read", "session", "none", "none", "none"),
  "project.reveal": descriptor("sessions.manage", "host", "none", "none", "none", true),
  "audit.read": descriptor("audit.read", "host", "none", "none", "none"),
  "audit.tail": descriptor("audit.read", "host", "none", "none", "none"),
  "config.write": descriptor("config.write", "host", "required", "authority", "challenge"),
  "settings.read": descriptor("config.read", "host", "none", "none", "none"),
  "settings.write": descriptor("config.write", "host", "required", "authority", "challenge"),
  "catalog.get": descriptor("catalog.read", "host", "none", "none", "none"),
  "broker.status": descriptor("broker.read", "host", "none", "none", "none", true),
  "usage.read": descriptor("usage.read", "host", "none", "none", "none", true),
  "host.watch": descriptor("sessions.read", "host", "none", "none", "none"),
  "session.watch": descriptor("sessions.read", "session", "none", "none", "none"),
  "controller.lease.acquire": descriptor(
    "sessions.control",
    "session",
    "required",
    "session",
    "none",
  ),
  "controller.lease.renew": descriptor(
    "sessions.control",
    "session",
    "required",
    "session",
    "none",
  ),
  "controller.lease.release": descriptor(
    "sessions.control",
    "session",
    "required",
    "session",
    "none",
  ),
  "prompt.lease.acquire": descriptor("sessions.prompt", "session", "required", "session", "none"),
  "prompt.lease.renew": descriptor("sessions.prompt", "session", "required", "session", "none"),
  "prompt.lease.release": descriptor("sessions.prompt", "session", "required", "session", "none"),
};
