import { describe, expect, test } from "bun:test";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { decodeProviderEventFrame, decodeProviderRequestFrame, decodeProviderResponseFrame, decodeTransportHandshakeFrame, encodeProviderEvent, encodeProviderFailure, encodeProviderRequest, encodeProviderSuccess, encodeTransportHandshake, encodeTransportHandshakeResult, PROVIDER_METHODS, type ProviderMethod, type WireValue } from "../src/machine-provider-v1.js";
const fixtures=fileURLToPath(new URL("../../../vendor/cmux-machine-provider-v1/fixtures/",import.meta.url));
const withoutLf=(b:Uint8Array)=>b.subarray(0,b.byteLength-1);
const control:[string,"request"|"response"|"event",ProviderMethod?][]=[["hello.request.ndjson","request"],["hello.success.ndjson","response","hello"],["negotiate-client-capabilities.request.ndjson","request"],["negotiate-client-capabilities.success.ndjson","response","negotiate_client_capabilities"],["snapshot.request.ndjson","request"],["snapshot.success.ndjson","response","snapshot"],["open-machine.request.ndjson","request"],["open-machine.success.ndjson","response","open_machine"],["durable-notice.event.ndjson","event"],["failure.response.ndjson","response","open_machine"],["close-machine.request.ndjson","request"],["close-machine.success.ndjson","response","close_machine"]];
describe("pinned serde frames",()=>{for(const[name,kind,method]of control)test(name,async()=>{const bytes=new Uint8Array(await readFile(`${fixtures}/control/${name}`));let encoded:Uint8Array;if(kind==="request")encoded=encodeProviderRequest(decodeProviderRequestFrame(withoutLf(bytes)));else if(kind==="event"){const event=decodeProviderEventFrame(withoutLf(bytes));encoded=encodeProviderEvent(event,event.delivery)}else{const response=decodeProviderResponseFrame(withoutLf(bytes),method!);encoded=response.error?encodeProviderFailure(response.id,response.error):encodeProviderSuccess(response.id,response.result!,response.capabilities)}expect(encoded).toEqual(bytes)});test("transport handshake",async()=>{const bytes=new Uint8Array(await readFile(`${fixtures}/stream/transport-handshake.ndjson`));expect(encodeTransportHandshake(decodeTransportHandshakeFrame(withoutLf(bytes)))).toEqual(bytes)});test("transport accepted",async()=>expect(encodeTransportHandshakeResult(true)).toEqual(new Uint8Array(await readFile(`${fixtures}/stream/transport-handshake-accepted.ndjson`))))});
const params:Record<ProviderMethod,Record<string,WireValue>>={hello:{token:"token",client:{name:"client",version:"1",supported_versions:[1]}},negotiate_client_capabilities:{capabilities:[]},subscribe_notices:{consumer_id:"consumer"},acknowledge_notice:{notice_id:"notice",sequence:18_446_744_073_709_551_615n},snapshot:{known_revision:9_007_199_254_740_992n},open_machine:{machine_id:"machine"},select_scope:{scope_id:"scope"},create_machine:{scope_id:"scope",mutation_id:"mutation"},connect_external_machine:{scope_id:"scope",specifier:"pair code",mutation_id:"mutation"},machine_lifecycle_snapshot:{scope_id:"scope"},rename_machine:{scope_id:"scope",machine_id:"machine",expected_version:0n,display_name:"name",mutation_id:"mutation"},delete_machine:{scope_id:"scope",machine_id:"machine",expected_version:0n,mutation_id:"mutation"},restore_machine:{scope_id:"scope",machine_id:"machine",expected_version:0n,mutation_id:"mutation"},purge_machine:{scope_id:"scope",machine_id:"machine",expected_version:0n,mutation_id:"mutation"},create_workspace:{machine_id:"machine",mode:"isolated",mutation_id:"mutation"},workspace_snapshot:{machine_id:"machine"},rename_workspace:{machine_id:"machine",workspace_id:"workspace",expected_version:0n,display_name:"name",mutation_id:"mutation"},delete_workspace:{machine_id:"machine",workspace_id:"workspace",expected_version:0n,mutation_id:"mutation"},restore_workspace:{machine_id:"machine",workspace_id:"workspace",expected_version:0n,mutation_id:"mutation"},purge_workspace:{machine_id:"machine",workspace_id:"workspace",expected_version:0n,mutation_id:"mutation"},invoke_action:{action_id:"action",mutation_id:"mutation",values:{count:9_007_199_254_740_992n}},close_machine:{connection_id:"connection"}};
test("every authoritative request variant is strict and lossless",()=>{expect(Object.keys(params)).toEqual([...PROVIDER_METHODS]);for(const method of PROVIDER_METHODS){const encoded=encodeProviderRequest({protocol:"cmux.machine-provider",version:1,id:"id",method,params:params[method]});const decoded=decodeProviderRequestFrame(withoutLf(encoded));expect(decoded.method).toBe(method);expect(()=>decodeProviderRequestFrame(new TextEncoder().encode(new TextDecoder().decode(withoutLf(encoded)).replace(/}\s*$/,',"extra":true}')))).not.toThrow();const nested=new TextEncoder().encode(new TextDecoder().decode(withoutLf(encoded)).replace(/"params":{/, '"params":{"extra":true,'));expect(()=>decodeProviderRequestFrame(nested)).toThrow()}});
test("object decoding preserves __proto__ map keys and rejects it as an unknown strict field", () => {
  const invoke = new TextEncoder().encode(
    '{"protocol":"cmux.machine-provider","version":1,"id":"invoke","method":"invoke_action","params":{"action_id":"stop","machine_id":"machine","mutation_id":"mutation","values":{"__proto__":"kept"}}}',
  );
  const decoded = decodeProviderRequestFrame(invoke);
  const values = decoded.params.values;
  if (values === null || typeof values !== "object" || Array.isArray(values))
    throw new Error("values map missing");
  const valuesRecord = values as Record<string, WireValue>;
  expect(Object.hasOwn(valuesRecord, "__proto__")).toBe(true);
  expect(valuesRecord["__proto__"]).toBe("kept");
  const unknown = new TextEncoder().encode(
    '{"protocol":"cmux.machine-provider","version":1,"id":"snapshot","method":"snapshot","params":{"__proto__":true}}',
  );
  expect(() => decodeProviderRequestFrame(unknown)).toThrow();
});
