import { expect,test } from "bun:test";
import { createHash } from "node:crypto";
import type { PortableControlStore,TicketBinding } from "@t4-code/portable-control-store";
import type { ResourceDriver } from "@t4-code/portable-driver";
import { MemoryProviderConnectionRegistry,type ProviderActiveConnection,type ProviderConnectionRegistry } from "../src/connection-registry.js";
import type { DuplexByteStream } from "../src/cmux-route-opener.js";
import { runProviderStream,PROVIDER_STREAM_AUDIENCE,PROVIDER_STREAM_PURPOSE } from "../src/stream-engine.js";
class AsyncSource implements AsyncIterable<Uint8Array>{readonly #values:Uint8Array[]=[];readonly #waiters:((value:IteratorResult<Uint8Array>)=>void)[]=[];#done=false;push(value:Uint8Array){const waiter=this.#waiters.shift();if(waiter)waiter({done:false,value});else this.#values.push(value)}finish(){this.#done=true;for(const waiter of this.#waiters.splice(0))waiter({done:true,value:undefined})}[Symbol.asyncIterator](){return{next:async():Promise<IteratorResult<Uint8Array>>=>{const value=this.#values.shift();if(value)return{done:false,value};if(this.#done)return{done:true,value:undefined};const deferred=Promise.withResolvers<IteratorResult<Uint8Array>>();this.#waiters.push(deferred.resolve);return deferred.promise}}}}
class MemoryDuplex implements DuplexByteStream{readonly writes:Uint8Array[]=[];readonly source=new AsyncSource();readonly endedSignal=Promise.withResolvers<void>();ended=false;closed=false;get readable(){return this.source}async write(chunk:Uint8Array){this.writes.push(chunk.slice())}async end(){this.ended=true;this.endedSignal.resolve()}async close(){this.closed=true;this.source.finish()}}
const token="control-bearer",ticket="abcdefghijklmnopqrstuvwxyzABCDEFG_123456",binding:TicketBinding={principalId:"principal",scopeId:"scope",audience:PROVIDER_STREAM_AUDIENCE,runtimeId:"runtime",runtimeGeneration:"runtime-generation",providerControlGeneration:createHash("sha256").update(token).digest("hex"),purpose:PROVIDER_STREAM_PURPOSE};
const frame=new TextEncoder().encode(JSON.stringify({protocol:"cmux.machine-provider",version:1,role:"transport",token,ticket})+"\n"),allowed={outcome:"allowed"as const,scopeIds:["scope"],effectiveCapabilities:[PROVIDER_STREAM_PURPOSE],policyRevision:"policy-1"};
const store=()=>{let consumed=false;return{consumeTicketForTransport:()=>consumed?{outcome:"rejected"as const}:(consumed=true,{outcome:"consumed"as const,binding})}as unknown as PortableControlStore};
const driver={resolveRuntimeRoute:()=>({outcome:"resolved",route:{kind:"cmux-v10",reference:"opaque"},generation:binding.runtimeGeneration})}as unknown as ResourceDriver;
async function registered(){const registry=new MemoryProviderConnectionRegistry();await registry.installControlGeneration({principalId:"principal",generation:binding.providerControlGeneration});await registry.register({...binding,connectionId:"connection",ticket});return registry}
test("coalesced command is exact and client-first half-close awaits runtime EOF",async()=>{const command=new TextEncoder().encode('{ "cmd" : "identify", "unknown": true }\n'),joined=new Uint8Array(frame.length+command.length);joined.set(frame);joined.set(command,frame.length);const client=new MemoryDuplex(),upstream=new MemoryDuplex();client.source.push(joined);client.source.finish();upstream.source.push(new TextEncoder().encode('{"protocol":10,"id":"x"}\n'));upstream.source.finish();const outcome=await runProviderStream({transport:client,identity:{principalId:"principal",transport:"internal",authority:{}},tickets:store(),driver,authorize:async()=>allowed,connections:await registered(),routeOpener:{open:async()=>upstream}});expect(outcome).toEqual({outcome:"clientClosed"});expect(upstream.writes).toEqual([command]);expect(new TextDecoder().decode(client.writes[0])).toBe('{"accepted":true}\n');expect(client.writes[1]).toEqual(new TextEncoder().encode('{"protocol":10,"id":"x"}\n'));expect(upstream.ended).toBe(true);expect(client.ended).toBe(true)});
test("runtime-first half-close waits for client EOF and settles both pumps",async()=>{const client=new MemoryDuplex(),upstream=new MemoryDuplex();client.source.push(frame);upstream.source.finish();const running=runProviderStream({transport:client,identity:{principalId:"principal",transport:"internal",authority:{}},tickets:store(),driver,authorize:async()=>allowed,connections:await registered(),routeOpener:{open:async()=>upstream}});await client.endedSignal.promise;client.source.finish();expect(await running).toEqual({outcome:"runtimeClosed"});expect(upstream.ended).toBe(true)});
test("revocation during route open never writes accepted true",async()=>{const client=new MemoryDuplex(),upstream=new MemoryDuplex(),registry=await registered();client.source.push(frame);const deferred=Promise.withResolvers<DuplexByteStream>(),openCalled=Promise.withResolvers<void>();const running=runProviderStream({transport:client,identity:{principalId:"principal",transport:"internal",authority:{}},tickets:store(),driver,authorize:async()=>allowed,connections:registry,routeOpener:{open:async()=>{openCalled.resolve();return deferred.promise}}});await openCalled.promise;await registry.close("connection");deferred.resolve(upstream);const outcome=await running;expect(outcome).toEqual({outcome:"rejected",reason:"revoked"});expect(client.writes.some(write=>new TextDecoder().decode(write)==='{"accepted":true}\n')).toBe(false);expect(upstream.closed).toBe(true)});
test("generation mismatch is included in the atomic claim before authorization and route open",async()=>{const wrongToken="wrong-token",wrongGeneration=createHash("sha256").update(wrongToken).digest("hex"),wrong=new TextEncoder().encode(JSON.stringify({protocol:"cmux.machine-provider",version:1,role:"transport",token:wrongToken,ticket})+"\n"),client=new MemoryDuplex();client.source.push(wrong);let authorized=0,opened=0,selectedGeneration="";const outcome=await runProviderStream({transport:client,identity:{principalId:"principal",transport:"internal",authority:{}},tickets:{consumeTicketForTransport:(selector:{providerControlGeneration:string})=>{selectedGeneration=selector.providerControlGeneration;return{outcome:"rejected"}}}as unknown as PortableControlStore,driver:{}as ResourceDriver,authorize:async()=>{authorized++;return allowed},connections:new MemoryProviderConnectionRegistry(),routeOpener:{open:async()=>{opened++;throw new Error()}}});expect(outcome).toEqual({outcome:"rejected",reason:"ticketRejected"});expect(selectedGeneration).toBe(wrongGeneration);expect(authorized).toBe(0);expect(opened).toBe(0)});
test("abort while waiting for the first handshake byte closes transport and settles",async()=>{const client=new MemoryDuplex(),controller=new AbortController(),running=runProviderStream({transport:client,identity:{principalId:"principal",transport:"internal",authority:{}},tickets:store(),driver,authorize:async()=>allowed,connections:await registered(),routeOpener:{open:async()=>{throw new Error("must not open")}},signal:controller.signal});controller.abort(new Error("cancelled"));expect(await running).toEqual({outcome:"revoked"});expect(client.closed).toBe(true)});
test("abort while authorization is pending closes transport without route admission",async()=>{const client=new MemoryDuplex(),controller=new AbortController(),started=Promise.withResolvers<void>(),authorization=Promise.withResolvers<typeof allowed>();client.source.push(frame);let opened=0;const running=runProviderStream({transport:client,identity:{principalId:"principal",transport:"internal",authority:{}},tickets:store(),driver,authorize:()=>{started.resolve();return authorization.promise},connections:await registered(),routeOpener:{open:async()=>{opened++;throw new Error("must not open")}},signal:controller.signal});await started.promise;controller.abort(new Error("cancelled"));expect(await running).toEqual({outcome:"revoked"});expect(client.closed).toBe(true);expect(opened).toBe(0);authorization.resolve(allowed)});
test("activation completion after cancellation absorbs activation and release rejection",async()=>{const client=new MemoryDuplex(),upstream=new MemoryDuplex(),controller=new AbortController(),started=Promise.withResolvers<void>(),activation=Promise.withResolvers<{outcome:"active";connection:ProviderActiveConnection}|{outcome:"rejected"}>();client.source.push(frame);const connections={activate:()=>{started.resolve();return activation.promise}}as unknown as ProviderConnectionRegistry;const running=runProviderStream({transport:client,identity:{principalId:"principal",transport:"internal",authority:{}},tickets:store(),driver,authorize:async()=>allowed,connections,routeOpener:{open:async()=>upstream},signal:controller.signal});await started.promise;controller.abort(new Error("cancelled"));activation.resolve({outcome:"active",connection:{connectionId:"connection",signal:new AbortController().signal,release:async()=>{throw new Error("release failed")}}});expect(await running).toEqual({outcome:"revoked"});await Promise.resolve()});
test("generation closure is principal-qualified even when bearer hashes collide",async()=>{const registry=new MemoryProviderConnectionRegistry(),generation=binding.providerControlGeneration,otherTicket=`${ticket}other`,otherBinding={...binding,principalId:"other"};await registry.installControlGeneration({principalId:"principal",generation});await registry.installControlGeneration({principalId:"other",generation});await registry.register({...binding,connectionId:"principal-connection",ticket});await registry.register({...otherBinding,connectionId:"other-connection",ticket:otherTicket});await registry.installControlGeneration({principalId:"principal",generation:"f".repeat(64)});const active=await registry.activate({...otherBinding,ticket:otherTicket});expect(active.outcome).toBe("active");if(active.outcome==="active")await active.connection.release()});
