name: Enclave
options:
  bundleIdPrefix: xyz.epsilver
  deploymentTarget:
    iOS: "26.0"
targets:
  Enclave:
    type: application
    platform: iOS
    sources:
      - Sources
      - Shared
      - Resources
    dependencies:
      - target: EnclaveWidgets
        embed: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: xyz.epsilver.enclave
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: Enclave-Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1"
        CODE_SIGNING_ALLOWED: YES
  EnclaveWidgets:
    type: app-extension
    platform: iOS
    sources:
      - WidgetSources
      - Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: xyz.epsilver.enclave.widgets
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: EnclaveWidgets-Info.plist
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1"
        CODE_SIGNING_ALLOWED: YES
